#!/usr/bin/env bash
# manages manage_my_process
# Check if an argument is provided
# Check if an argument is provided
if [ -z "$1" ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
fi

# Check the provided argument
case "$1" in
    start)
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f /var/run/my_process.pid ]; then
            echo "manage_my_process stopped"
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
        else
            echo "PID file not found. manage_my_process might not be running."
        fi
        ;;
    restart)
        if [ -f /var/run/my_process.pid ]; then
            echo "manage_my_process restarted"
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
            ./manage_my_process &
            echo "$!" > /var/run/my_process.pid
        else
            echo "PID file not found. Starting manage_my_process."
            ./manage_my_process &
            echo "$!" > /var/run/my_process.pid
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0                    
